<?php

return [
    'endpoint' => env('SERAP_INGEST_ENDPOINT', 'https://github.com/luang-dev/serap'),
    'api_key' => env('SERAP_API_KEY', null),
    'ingest' => [
        'driver' => env('SERAP_INGEST_DRIVER', 'file'),
        'batch_size' => env('SERAP_INGEST_BATCH_SIZE', 100),
        'redis' => [
            'connection' => env('SERAP_REDIS_CONNECTION', 'default'),
            'key' => env('SERAP_REDIS_KEY', 'serap:logs'),
        ],
    ],
    'sensitive_keys' => [
        'api_key',
        'password',
        'token',
        'secret',
        'key',
        'auth_token',
        'access_token',
        'refresh_token',
        'client_secret',
        'client_id',
        'session_token',
        'cookie',
        'password_confirmation',
        'authorization',
        'laravel-session',
        'set-cookie',
        'xsrf_token',
        'csrf-token',
        'pin',
        'mpin',
        'otp',
        'm_pin',
        'mfa',
        'api_token',
        'secret_key,',
        'code',
    ],
    'mask' => '********',
];
